# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelink',
            name='title',
            field=models.CharField(default='Main Image', max_length=50),
            preserve_default=False,
        ),
    ]
